# Generated by Django 4.0.2 on 2022-09-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill',
            name='CHOOSE_TYPE',
            field=models.CharField(choices=[('market', 'market'), ('cold storage', 'cold storage')], default='cold storage', max_length=50),
        ),
    ]
