# Generated by Django 4.0.2 on 2022-09-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold', '0003_remove_mill_address_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('graduation', models.CharField(max_length=100)),
                ('technologies', models.TextField()),
            ],
        ),
    ]
