# Generated by Django 4.0.2 on 2022-11-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold', '0004_excel'),
    ]

    operations = [
        migrations.CreateModel(
            name='hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('graduation', models.CharField(max_length=100)),
                ('technologies', models.TextField()),
            ],
        ),
    ]
