# Generated by Django 4.0.2 on 2022-11-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold', '0005_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='resume',
            field=models.TextField(default='NULL'),
        ),
    ]
