# Generated by Django 4.0.2 on 2023-02-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold', '0006_hello_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='fill name')),
                ('second_name', models.CharField(max_length=200)),
            ],
        ),
    ]
