# Generated by Django 4.0.2 on 2023-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold', '0007_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='hello fill it'),
        ),
    ]
