# Generated by Django 4.0.2 on 2023-02-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold', '0009_alter_officer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='hello fill it'),
        ),
    ]
