# Generated by Django 4.0.2 on 2023-02-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold', '0010_alter_officer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
