# Generated by Django 4.0.2 on 2023-02-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold', '0011_alter_officer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=1, null=True),
        ),
    ]
