# Generated by Django 4.0.2 on 2023-02-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold', '0014_alter_officer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], default="don't worry", max_length=20),
        ),
    ]
